### ISSUE TITLE
Add CodeGen for Rust (hyper)

### ISSUE THREAD

**Issue by ashitaprasad** [foss42/apidash#149]
**Tell us about the task you want to perform and are unable to do so because the feature is not available**

Add CodeGen for Rust
Library - https://hyper.rs/

Guidelines for adding a codegen - https://github.com/foss42/apidash/discussions/80

**Comment by AcousticDeveloper** [comment]
I've started working on this issue, will open a PR soon.

**Comment by Clasherzz** [comment]
I am working on this but hyper doesnt support multipart forms . So should i just show error saying unsupported when multiple forms are made .

**Comment by Clasherzz** [comment]
The current version of hyper doesn't support sending form data requests .This can be workaround by serializing the data . But should it say the formdata is not supported by the library as it is more accurate than serializing and sending. Especially if endpoint is expecting formdata.

**Comment by ashitaprasad** [comment]
There is a similar query here - https://www.reddit.com/r/rust/comments/4nifd6/hyper_and_forms_post/

For multipart, you can use another library that works well with hyper.

**Comment by Clasherzz** [comment]
`async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let https = HttpsConnector::new();
    let client = Client::builder().build::<_, hyper::Body>(https);
    let url = "https://api.apidash.dev".parse::<Uri>().unwrap();
    let req = Request::builder()
              .method("GET")
              .uri(url)        
              .header("Accept-Encoding", "sdsd");
              .body(Body::from(body))?;

        
  
    let res = client.request(req).await?;
    let status = res.status();
    let body_bytes = hyper::body::to_bytes(res).await?;
    let body = String::from_utf8(body_bytes.to_vec())?;

    println!("Response Status: {}", status);
    println!("Response: {:?}", body);
    println!("1");


    let reqwest_client = ReqwestClient::builder()
        .danger_accept_invalid_certs(true) // Optional: Accept invalid certificates
        .build()?;
        println!("2");
    let form = Form::new()
        .text("field1", "value1")
        .text("field2", "value2");
        
        println!("3");
    let reqwest_response = reqwest_client
        .post("https://example.com/upload")
        .multipart(form)
        .send()
        .await?;
        println!("4");
    println!("Reqwest Status: {}", reqwest_response.status());
    let body = reqwest_response.text().await?;
    println!("Reqwest Body: {}", body);





    Ok(())
}
             `

would something like this work ? I am quite unfamiliar about two requests going to the same point.

**Comment by Clasherzz** [comment]
Would it be possible to have the cargo.toml file that was used to test reqwest library. I have implemented a similar way as shown in rust reqwest codegen file for hyper multipart . But there are a lot of version or dependency errors.

**Comment by ashitaprasad** [comment]
@Clasherzz That support was added by @Tanish2002 
You can definitely reach out to him and drop a message in case you need any help

**Comment by Tanish2002** [comment]
Hi @Clasherzz
I, fortunately, had the test app I used for creating other rust codegens. It does have other irrelevant dependencies, you can remove the ones you don't need.

```toml
[package]
name = "reqester"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13.3"
actix-multipart = "0.6.1"
actix-rt = "2.9.0"
actix-web = "4.5.1"
awc = { version = "3.4.0", features = ["openssl"] }
bytes = "1.6.0"
curl = "0.4.46"
futures = "0.3.30"
mime_guess = "2.0.4"
multipart = { version = "0.18.0", features = ["client"] }
openssl = "0.10.64"
reqwest = { version = "0.11.24", features = ["blocking", "json", "multipart"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
tokio = { version = "1.36.0", features = ["full"] }
ureq = { version = "2.9.6", features = ["json"] }
```
